# Generated by Django 3.1.6 on 2021-05-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_sender', models.TextField()),
                ('mail_receiver', models.TextField()),
                ('mail_subject', models.TextField()),
                ('mail_body', models.TextField()),
                ('mail_attachements', models.FileField(upload_to='')),
            ],
        ),
    ]
