# Generated by Django 3.1.6 on 2021-05-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20210501_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_receiver',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_sender',
            field=models.EmailField(max_length=254),
        ),
    ]
