# Generated by Django 3.1.6 on 2021-05-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_auto_20210502_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_attachements',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_body',
            field=models.TextField(blank=True, default='--empty--', null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_subject',
            field=models.TextField(blank=True, default='No Subject Mail', null=True),
        ),
    ]
